version: '3'
services:
    mysql:
        image: hafidnid/mysql:8.0.30
        restart: unless-stopped
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=1
        ports:
          - "3306:3306"
        networks:
          - my-network_nmms

    rabbitmq:
      image: hafidnid/rabbitmq:3.12.9-management
      hostname: rabbit
      container_name: rabbitmq 
      restart: always
      environment:
        RABBITMQ_ERLANG_COOKIE: rabbitcookie
      ports:
        - "15672:15672"
        - "5672:5672"
      networks:
        - my-network_nmms

    model-server:
      image: hafidnid/model_image:latest
      container_name: model-server
      restart: always
      ports:
        - "6000:6000"
      depends_on:
        - rabbitmq
      networks:
        - my-network_nmms

    app_bio:
      image: hafidnid/app_biomedicale_db_local_finale_f:latest
      container_name: app_bio
      restart: always
      depends_on:
        - mysql
        - rabbitmq
      ports:
        - "8080:8080"
      environment:
        SPRING_RABBITMQ_HOST: rabbitmq 
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysql:3306/appbiomedica?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
            "spring.jpa.hibernate.ddl-auto" : "none"}'
      networks:
        - my-network_nmms

volumes:
  db:

networks:
  my-network_nmms:
    driver: bridge